### ISSUE TITLE
Not possible to set brightness and color for a light from HA to Loxone

### ISSUE THREAD

**Issue by johny-mnemonic** [JoDehli/PyLoxone#100]
I am not sure whether I am doing something wrong or whether there is a bug in HA or PyLoxone, but I am unable to set brighness and color of the light in Loxone from HA.

When I send just `rgb_color` i.e.:
```
service: light.turn_on
target:
  entity_id: light.led_kitchen
data:  
  rgb_color: [0,0,255]
```
It set's the color of the light correctly, but with 100% brightness.
And when I try to add brightness to the service call:
```
service: light.turn_on
target:
  entity_id: light.led_kitchen
data:  
  rgb_color: [0,0,255]
  brightness: 153
```
It sets the brightness correctly in Loxone, but it switches the light to white color resetting any color it was set to.
Looks like if PyLoxone expects that only white dimmable lights have brightness. I have a few of white dimmable lights controlled this way and everything works fine. This is my first RGB light that I am trying to integrate this way...

I noticed in Loxone live view, that the LightController is setting the color and brightness as a combination of both simply by mixing brightness into rgb color, so I tried to do the same in HA:
```
service: light.turn_on
target:
  entity_id: light.led_kitchen
data: 
  rgb_color:
  - '{{ (states.light.led_kitchen.attributes.rgb_color[0] * states.light.led_kitchen.attributes.brightness/255) | int }}'
  - '{{ (states.light.led_kitchen.attributes.rgb_color[1] * states.light.led_kitchen.attributes.brightness/255) | int }}'
  - '{{ (states.light.led_kitchen.attributes.rgb_color[2] * states.light.led_kitchen.attributes.brightness/255) | int }}'
```
Unfortunately that again sets the color correctly but with 100% brightness...

The motivation and other details:
I have Loxone as primary system and HA used mainly to integrate things that doesn't work with Loxone.
Now I have got the LED RGB strip which has it's own remote control which my kids love, so I can't dump it ;-)

I flashed the LED strip controller with ESPHome and with the help of a few automations I am able to control it from Loxone without any trouble. But I also want to get the state of the light strip back from HA to Loxone for when it is controlled by the remote control.

Could you please check it and advice what is the correct way to control brightness and color of RGB(W) lights through PyLoxone?

**Comment by JoDehli** [comment]
I have no lights so I never had this problem. Home assistant sents 2 events if you want to change the color and the brightness. So to fix this you must sent first the color and after this the brightness. This should do the trick. I did not test it because as I mentioned I have no lights.  Hope this helps.

**Comment by johny-mnemonic** [comment]
That's unfortunately the first thing I tried and no luck.
As I wrote, when you send just the rgb_color, it correctly sets the color and sets brightness to 100%. And then if you try to send any value for brightness, it resets the color to white (RGB 255,255,255) and sets the correct brightness.

I tried all the ways to set color and each of the works correctly, but once you try to set brightness in any way from HA, the color is gone. I tried them all, 'brightness', 'brightness_pct' and 'brightness_step_pct'. All reliably sets brightness, while dropping any color information...

My bet would be, that Loxone only accepts setting color together with brightness in single commnad, but I am just guessing here.

**Comment by JoDehli** [comment]
I know that I can test it but I do not need the lights. I spent hours to integrate and and tested it with virtual lights. In the past I had a lot of work that it works like now. I think they work as expected when you control it via ha. That was the goal in the fist place. If someone improves it without making major changes they can sent me a pull request. You can try openhab maybe they support this feature.

**Comment by JoDehli** [comment]
What you can also do if you are not happy with the way loxone is implemented you can make a web socket call thru my binding as explained in the read me. 

For example if you want a rgb color thru one output of a light controller you can do it like this: 

![image](https://user-images.githubusercontent.com/32484282/155110792-dc594449-4483-48f1-92eb-50a31cc912c5.png)

You can connect that with a button or a script. I think then you can do what you want.

**Comment by JoDehli** [comment]
And by the way if you want to simulate a plus command you can do it like this:
![image](https://user-images.githubusercontent.com/32484282/155111351-91b70b02-7323-4c3e-b2ec-487b5025d4cc.png)

**Comment by JoDehli** [comment]
And a temperature is set like this:
![image](https://user-images.githubusercontent.com/32484282/155112057-d53531fb-b2bd-4305-a119-0b37c36de651.png)

**Comment by johny-mnemonic** [comment]
> I know that I can test it but I do not need the lights. I spent hours to integrate and and tested it with virtual lights. In the past I had a lot of work that it works like now. I think they work as expected when you control it via ha. That was the goal in the fist place. If someone improves it without making major changes they can sent me a pull request. You can try openhab maybe they support this feature.
I know you spent a lot of your time developing something you are not even using yourself, just for us the users of PyLoxone and I am grateful for that. In case it sounded like I demand a fix I am deeply sorry, as that was not my intention.
It just looked like you don't trust me that it is now broken (most probably due to a change in HA or Loxone), so I tried to provide few simple steps to reproduce this bug.

It is not about whether I am happy with the way it is implemented, it simply doesn't work now for colored lights (not possible to control the brightness). It works fine only for single color lights and simple switch lights.

In case you have no desire to fix or even verify this bug it's perfectly OK as it's your time, I just wanted to report a bug, that's all.

Thanks a lot for these hint's for direct websocket usage. That's a great workaround. I just made the HA -> Loxone control of RGB working thanks to it.
Will try to check the code, whether it would be easy to fix, but I am more sysad than coder...

**Comment by JoDehli** [comment]
Can you try the master branch a last time. Maybe I found what was causing the problem. I also changed the on behaviour. It should now behave the same as in loxone.

**Comment by johny-mnemonic** [comment]
Thanks for your time, but unfortunately the behavior is still the same.

When I turn on the lightcontroller in HA it does the same thing as calling this:
```
service: loxone.event_websocket_command
data:
  uuid: 1071d041-014a-9e99-ffffd7846630eb23
  value: on
```
It activates the "more light" default scene ("Enables lightscene 9 (All on)" according to docs). So it's the same as if you send pulse to the `O` input of the lightcontroller.
This looks like an obvious way to implement it so I am not surprised you did it this way. I wouldn't consider this as a bug per se.
I just think it would make more sense to improve the behavior and activate the first light scene with `plus` command instead as that's what you usually want when you activate the light in the room. Instead of blasting all lights at full power.

Regarding the brightness of rgb lights.
```
service: loxone.event_websocket_command
data:
  uuid: 1071d041-014a-9e99-ffffd7846630eb23/AI3
  value: hsv(37,100,60)
```
Calling this, results in having the correct color and 60% brightness in Loxone.
Precisely:
```
color_mode: hs
brightness: 153
hs_color:
  - 36.941
  - 100
rgb_color:
  - 255
  - 156
  - 0
xy_color:
  - 0.574
  - 0.406
color_temp: 0
uuid: 1071d041-014a-9e99-ffffd7846630eb23/AI3
room: ''
category: ''
device_typ: ColorPickerV2
platform: loxone
```
While calling this:
```
service: light.turn_on
target:
  entity_id: light.led_kitchen
data:  
  hs_color: [37,100]
  brightness_pct: 60
```
Results in white light with 60% brightness.
```
color_mode: color_temp
brightness: 153
color_temp: 153
hs_color:
  - 54.768
  - 1.6
rgb_color:
  - 255
  - 254
  - 250
```
Maybe it's interesting, that it changed the mode from `hs` to `color_temp`. 
On the other hand when you call just with the color:
```
service: light.turn_on
target:
  entity_id: light.led_kitchen
data:  
  hs_color: [37,100]
```
it sets the color correctly and it is still reported in `hs` mode. The only downside is, that it then always has 100% brightness.

Looks like even when you provide both information (hs_color and brightness) it doesn't combine them together to send correct `hsv` to Loxone, but it sends them in two steps. And sending the brightness alone seems to result in sending `temp` command instead of `hsv` to Loxone, which resets the color information...
It seems like it first sends `hsv(37,100,100)` and then `temp(60,6500)`, filling the "missing" values with the max value in both cases. At least when I send these using websocket I get the same result in Loxone as if I use the `light.turn_on` service in HA.

My workaround using websocket does exactly what would need to be done in the code:
```
service: loxone.event_websocket_command
data:
  uuid: 1071d041-014a-9e99-ffffd7846630eb23/AI3
  value: >
    {%- set hue = states.light.led_rgb_kitchen.attributes.hs_color[0] %}
    {%- set sat = states.light.led_rgb_kitchen.attributes.hs_color[1] %}
    {%- set br = states.light.led_rgb_kitchen.attributes.brightness/2.55 %}
    hsv({{ hue | round(2) | default(0)  }},{{ sat | round(2) | default(0) }},{{ br | round(2) | default(0) }})
```
It combines hs color information with brightness into single `hsv` call to Loxone.

**Comment by JoDehli** [comment]
That nearly impossible because I changed it. Have you copied it manually from git or over hacs? You must copy manually. The on command should send a plus instead of a on command.

**Comment by JoDehli** [comment]
Regarding the on command. I thought I changed it everywhere but I saw there are some more on commands. You can change it int light.py itself and see it works as accepted. For the replace the "on" with the "plus" in the light.py. 

Regarding the brightness and color. I tried it on a RGB light itself. I think it was as subcontrol of a light controller. And I used the GUI for the service. The GUI allows the color or the temperature not both which makes sense for me. If you pass a temperature it switches to temperature mode. And on my testing it works perfect. 

For me a colour to a light controller itself is difficult because a light controller can consist of RGB and normal lights which does not support RGB. I tried it only on subcontrols.

**Comment by JoDehli** [comment]
@johny-mnemonic I replaced now all on commands with the plus command. And now I can not turn on some of my test lights anymore. In Loxone the can also not switched by the plus sign. I can only switch them by choosing a scene. But in Home Assistant the scenes are only available when the light is already on. So when I leave the changes like this some users can not switch the lights anymore.  Any succession why this happens? Why are the plus button on the loxone app and browser app are not working for this lights?

**Comment by johny-mnemonic** [comment]
Thanks for your time playing with this. I would say that in case there is any issue with using the `plus` command instead of `on` , then just don't spend more time with it. It is nothing major as you can easily workaround it without messing with websocket just by activating the scene you want. I just thought it would behave better this way...
I wonder what kind of light can't be turned on by plus command as I have most of the lights configured like that in my house. I went through all my light blocks in Loxone config now and haven't found a single one that refused to turn on using the plus input. Maybe it behaves differently through websocket then when you connect a button to a `plus` input of the light block 🤷‍♂️. I can test that later.

Regarding the color temperature I thing this is misunderstanding. I am always working with subcontrols the same as you do and I never intentionally set color temperature from HA.
The thing is, that when you send just a brightness change from HA to a rgb light (the subcontrol) it seems to be implemented the way that it sends the color temperature instead of sending color together with brightness (hsv). Which results in resetting the color information.
Did you try to send brightness to a RGB subcontrol? This is the only thing that doesn't work correctly for me. Everything else seems to work fine.

**Comment by johny-mnemonic** [comment]
I have only 3 RGB lights and I discovered it on the least populated light controller:
![loxone_light_kitchen](https://user-images.githubusercontent.com/1143074/156079706-87ed2e32-aeed-498f-af16-0ad6a11fd3fc.png)
It has two switches and RGB light.
The other two are more populated, one without any switch light at all. All dimmers and one RGB. And the second one has 3 dimmers, RGB and switch:
![loxone_light_bath2](https://user-images.githubusercontent.com/1143074/156079923-7503ba43-372c-4947-b49c-ef9ec5555c64.png)
All of them behaves consistently with what I described in previous posts though.

So you are saying, that when you send this from HA:
```
service: light.turn_on
target:
  entity_id: light.SUBCONTROL_ENTITY
data:
  hs_color: [0, 100]
  brightness:_pct 60
```
You are getting red light with 60% brightness in Loxone?

**Comment by JoDehli** [comment]
@johny-mnemonic I changed again the light behavior for the lights on the master branch. Can you try it on the sub-controls of your first lightcontroller in the previous post. The one with 2 switches and one rgb. There I tried it with brightness only, and brightness with temp and rgb color. 

If this works I try the next one.

**Comment by johny-mnemonic** [comment]
I am sorry, but it's still the same :-(
```
service: light.turn_on
target:
  entity_id: light.led_podlaha_kuchyn
data:
  #hs_color: [100,100]
  rgb_color: [0,100,0]
  #brightness_pct: 60
```
No matter whether I try with `rgb_color` or `hs_color` once I add brightness it changes mode from `hs` to `color_temp` which resets the color information...

**Comment by JoDehli** [comment]
Do you use the GUI? I tried it only with the gui.

**Comment by JoDehli** [comment]
Ok now I have tested everything and it works perfect on my system. I can set the brightness, color and temp on subcontrols. I removed the ability to change the brightness and color on the main light controller. It fits not in the loxone way of doing it. So now it haves exactly like in Loxone. 

I tried the following:

```
service: light.turn_on
data:
  rgb_color:
    - 255
    - 100
    - 100
  brightness_pct: 50
target:
  entity_id: light.rgb_5
```
```
service: light.turn_on
data:
  rgb_color:
    - 255
    - 100
    - 100
  brightness: 125
target:
  entity_id: light.rgb_5
```

```
service: light.turn_on
data:
  color_name: blue
  brightness_pct: 50
target:
  entity_id: light.rgb_5
```

```
service: light.turn_on
data:
  kelvin: 2200
target:
  entity_id: light.rgb_5
```
