### ISSUE TITLE
Not able to get readings from miniserver

### ISSUE THREAD

**Issue by danielvancamp** [JoDehli/PyLoxone#126]
First of all, thanks a lot for the effort you put into making and maintaining this. I'm rather new to Home Assistant, but with the integration of Loxone i think i'll never go back to the Loxone GUI again. 😍 

**Which Model do you use from loxone? Miniserver? Gen1 or Gen2?**
Gen1

**Which software version does your loxone use?**
13.0.7.26

**How did you install HomeAssistant? Over Hassio oder manual install?**
Docker container (linuxservers)

**Which Version do you use of HomeAssistant?**
Home Assistant 2022.7.7

**Describe the bug**
Installed PyLoxone through HACS which went like a charm. When configuring my server, it detects all my entities but after finishing up it throws me 2 errors. 
![image](https://user-images.githubusercontent.com/8830345/181934697-cfdb6706-9802-4a89-be6b-637d7e4a8df7.png)
![image](https://user-images.githubusercontent.com/8830345/181934707-03febcf7-685c-44fa-8812-c0f7220145d9.png)

I've checked countless things already, but like i mentioned already, i just started using Home Assistant so not sure what is going wrong here. I've written a small nodeJS server which connects to loxone through a WS with the same creds, so i'm positive the creds do work. I would also assume the same since it did connect to the miniserver and fetched all the entities. 

I'm probably missing something obvious, sorry if this is the case. 

Hope you find the time to have a look at this. 

**Paste the error log with the following settings:**
```yaml
Logger: custom_components.loxone.miniserver
Source: custom_components/loxone/miniserver.py:106
Integration: PyLoxone ([documentation](https://github.com/JoDehli/PyLoxone), [issues](https://github.com/JoDehli/PyLoxone/issues))
First occurred: 7:04:29 PM (1 occurrences)
Last logged: 7:04:29 PM

Error connecting to loxone miniserver #1
```

```yaml
Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:164
Integration: Binary sensor ([documentation](https://www.home-assistant.io/integrations/binary_sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+binary_sensor%22))
First occurred: 7:04:29 PM (1 occurrences)
Last logged: 7:04:29 PM

The loxone platform for the binary_sensor integration does not support platform setup. Please remove it from your config.
```

Let me know if you need any additional information. 

Kind regard!
Daniel

**Comment by JoDehli** [comment]
@danielvancamp do you have configured your loxone via yaml? If so remove it and configure via GUI. 

Or do you have any custom sensor defined via yaml? If so remove it and try it again.

**Comment by danielvancamp** [comment]
Hello @JoDehli, good morning!
Thanks for you reply. 

I installed it through the GUI.
No custom sensors are installed, however i have one custom service(?) configured in the configuration.yaml. 

This is my current configuration.yaml
``` yaml
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

rest_command:
  ring:
    url: http://192.168.1.35/api/sonos/ring

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
``` 

We are talking about the configuration.yaml right? :D

**Comment by JoDehli** [comment]
@danielvancamp the ring should not be the problem. I do not know at moment what could be the problem. Sorry. 

How did you install pyloxone? Is it the newest pyloxone?

**Comment by danielvancamp** [comment]
@JoDehli no worries! I'll try to dig a little deeper in the coming days. 
I installed it through HACS, currently i'm on the latest version 0.3.13, i tried with some previous versions as well, no success there either :( 

I'll try to run an clean setup and see if i get it running like that!

**Comment by JoDehli** [comment]
@danielvancamp the binary sensors an introduced maybe 2 versions ago. The error massage comes from the binary sensor. So try the version before. But remove the loxone custom components folder manually. I had some problems by downgrading over hacs. I do no know why but it did not downgrade over hacs.

**Comment by JoDehli** [comment]
@danielvancamp you can try it with special log output. Maybe we can find out what went wrong. Add this to your configuration.yaml

```yaml
logger:
  default: warning
  logs:
    homeassistant: warning
    homeassistant.helpers: warning
    custom_components.loxone: debug
    custom_components.loxone.api: debug
```
