### ISSUE TITLE
Issue with Sensors

### ISSUE THREAD

**Issue by jere1985** [JoDehli/PyLoxone#128]
**Which Model do you use from loxone? Miniserver? Gen1 or Gen2?**
Gen 1

**Which software version does your loxone use?**
 12.2.12.1

**How did you install HomeAssistant? Over Hassio oder manual install?**
Manual Install

**Which Version do you use of HomeAssistant?**
Home Assistant 2022.8.7

**Describe the issue**
I use the PyLoxone to be able to use my Sonos Box to play a sound when someone presses the bell of my Loxone Intercom.
After updating my HA, PyLoxone the automation started to fail but i don't know why for the moment.

**Paste the error log with the following settings:**
When restarting my HA i see the following in the log files.

**Logger**: homeassistant.components.binary_sensor
**Source**: helpers/entity_platform.py:193
**Integration**: Binary Sensor ([documentation](https://www.home-assistant.io/integrations/binary_sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+binary_sensor%22))
**First occurred**: 13:14:46 (1 occurrences)
**Last logged**: 13:14:46

The loxone platform for the binary_sensor integration does not support platform setup. Please remove it from your config.

I thought there was an error in my config so removed all custom config from sensor.yaml & Automation.yaml but still the same error. (Don't know if it is related)

Below is the sensor.yaml & automation.yaml that used to work, when testing the automation from the webinterface my sonos bar makes the sound but when pressing the bell button on the intercom nothing happens in HA.

What am i missing, is my configuration wrong or is there a new way to configure the intercom?

Thanks in advance for the help.

```yaml
- name: "Loxone Intercom - Bell"
  platform: loxone
  uuidAction: "16a8438f-02fd-fbda-ffff2ceb37ef60ed"
  unit_of_measurement: ""

#- name: "Loxone Intercom - LastBellEvents"
#  platform: loxone
#  uuidAction: "16a8438f-02fd-fbd5-ffff2ceb37ef60ed"
#  unit_of_measurement: ""

#- name: "Loxone Intercom - Version"
#  platform: loxone
#  uuidAction: "16a8438f-02fd-fbd6-ffff2ceb37ef60ed"
#  unit_of_measurement: ""

```
```yaml
- id: '1633173542334'
  alias: Ring Deurbel
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.loxone_intercom_bell
    to: '1.0'
    from: '0.0'
  condition: []
  action:
  - service: sonos.snapshot
    data:
      entity_id: media_player.woonkamer
  - service: media_player.volume_set
    target:
      entity_id: media_player.woonkamer
    data:
      volume_level: 0.5
  - service: media_player.play_media
    target:
      entity_id: media_player.woonkamer
    data:
      media_content_id: http://10.0.10.116:8123/local/deurbel.mp3
      media_content_type: music
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: media_player.play_media
    target:
      entity_id: media_player.woonkamer
    data:
      media_content_id: http://10.0.10.116:8123/local/knocking.mp3
      media_content_type: music
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: sonos.restore
    data:
      entity_id: media_player.woonkamer
  mode: single
```
