### ISSUE TITLE
Toggling instead sending ON

### ISSUE THREAD

**Issue by Nerkyator** [JoDehli/PyLoxone#130]
**Which Model do you use from loxone? Miniserver? Gen1 or Gen2?**
`Gen2`

**Which software version does your loxone use?**
`13.0.7.26`

**How did you install HomeAssistant? Over Hassio oder manual install?**
`Hassio`

**Which Version do you use of HomeAssistant?**
`2022.09.1`

**Describe the bug**

I have a strange behavior: 

Example 1:
Studio light is OFF
Time automation to put Studio light to OFF at 07:30PM 
**Works (it does nothing)**

Example 1:
Studio light is OFF
Time automation to put Studio light to ON at 09:30AM 
**Works (light lights up)**

Example 1:
Studio light is ON
Time automation to put Studio light to ON at 10:30AM 
**Doesn't work: light will switch to off**

It seems that when a light is ON and something should put it to ON, instead to send the ON message (so nothing to do) it will toggle the entity.
My automation is quite simple:

```
alias: TEST
description: ""
trigger:
  - platform: time
    at: "10:30:00"
condition: []
action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.luce_studio
mode: single
```

**Comment by JoDehli** [comment]
Try to fix your automation by checking if the state is already on and only execute it if it is not on. So the trigger should not appear.

**Comment by JoDehli** [comment]
You must use the pyloxone websocket command if you want to make sure that it stays on. 

For example like this: 
```yaml
service: loxone.event_websocket_command
data:
  uuid: 169b034c-0367-8a87-ffffd9dde30b97d9
  value: "on"
```

You can get the uuid in Gui like so:

![image](https://user-images.githubusercontent.com/32484282/193403816-51f06f25-cb7f-45a6-b74b-5ea4ec8065e0.png)

If you sent a on command it will stay on if it is already on and it switches on if it is off.

**Comment by JoDehli** [comment]
@Nerkyator 
Something like this: 

```yaml
alias: Neue Automatisierung
description: ''
trigger:
- platform: time
  at: '12:00:00'
condition: []
action:
- service: loxone.event_websocket_command
  data:
    uuid: 169b034c-0367-8a87-ffffd9dde30b97d9
    value: 'on'

```
