### ISSUE TITLE
Entities show up but are unusable.

### ISSUE THREAD

**Issue by pieter-jangoeman** [JoDehli/PyLoxone#132]
**Which Model do you use from loxone? Miniserver? Gen1 or Gen2?**
Gen1

**Which software version does your loxone use?**
13.7.26

**How did you install HomeAssistant? Over Hassio oder manual install?**
As OS

**Which Version do you use of HomeAssistant?**
Home Assistant 2022.9.7
Supervisor 2022.09.1
Operating System 9.0
Frontend 20220907.2 - latest

**Describe the bug**
I'm able to load a lot of my entities in home assistant, but, nothing is usable, lights all seem to be on, but I can't switch anything on or off, temperatures used to come in fine from the heating blocks, but now, after deleting everything and loading it again, they don't show up anymore. 

```
![Screenshot 2022-10-04 215836](https://user-images.githubusercontent.com/9072632/193913941-2f865601-03df-42b2-a37a-279d515d5f98.png)

**Comment by pieter-jangoeman** [comment]
Update, I've just tried with the 'scene delay' value in the configuration on '0', this seems to work better. Any idea why?

**Comment by JoDehli** [comment]
You can disable scene generation completely for the beginning. 

Can you provide logs? Search in already closed issues how to configure log for the best log output. I already mentioned it a view times.

**Comment by JoDehli** [comment]
@pieter-jangoeman any progress on that topic? 

Add this logger configuration to ha and paste the log on startup:

```yaml
logger:
  default: warning
  logs:
    homeassistant: warning
    homeassistant.helpers: warning
    custom_components.loxone: debug
    custom_components.loxone.api: debug
```
