### ISSUE TITLE
Unable to prepare setup for platform loxone.climate

### ISSUE THREAD

**Issue by vicfalls** [JoDehli/PyLoxone#160]
**Which Model do you use from loxone? Miniserver? Gen1 or Gen2?**
Miniserver Gen1

**Which software version does your loxone use?**
13.0.7.26

**How did you install HomeAssistant? Over Hassio oder manual install?**
Hassio

**Which Version do you use of HomeAssistant?**
Home Assistant 2023.1.7
Supervisor 2023.01.1
Operating System 9.5

**Describe the bug**

**Paste the error log with the following settings:**
```yaml
Logger: homeassistant.setup
Source: setup.py:340 
First occurred: 13:10:01 (2 occurrences) 
Last logged: 13:10:01

Unable to prepare setup for platform loxone.climate: Platform not found (cannot import name 'TEMP_CELSIUS' from 'homeassistant.components.climate' (/usr/src/homeassistant/homeassistant/components/climate/__init__.py)).

023-01-28 13:10:01.266 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform loxone.climate: Platform not found (cannot import name 'TEMP_CELSIUS' from 'homeassistant.components.climate' (/usr/src/homeassistant/homeassistant/components/climate/__init__.py)).
2023-01-28 13:10:01.431 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform loxone.climate: Platform not found (cannot import name 'TEMP_CELSIUS' from 'homeassistant.components.climate' (/usr/src/homeassistant/homeassistant/components/climate/__init__.py)).
```
