### ISSUE TITLE
IRoomController

### ISSUE THREAD

**Issue by Enrique555** [JoDehli/PyLoxone#161]
**Which Model do you use from loxone? Miniserver? Gen1 or Gen2?**
Miniserver
**Which software version does your loxone use?**
Firmware 10.2.3.26
**How did you install HomeAssistant? Over Hassio oder manual install?**
Home Assistant Container
**Which Version do you use of HomeAssistant?**
Home Assistant 2023.1.1
Frontend 20230104.0 - latest 

**Describe the bug**
I have followed the example for changing the target temperature, 'tempTarget', from the documentation and my script does nothing. I use the 'setComfortTemperature' function, but it doesn't work. I think it's because my IRC is not 'IRoomControllerV2', but 'IRoomController'. It's possible? If so, how could I upgrade to IRoomControllerV2? 

**This is my script In HA:**
```
alias: Subir Temperatura Deseada
sequence:
  - service: loxone.event_websocket_command
    data_template:
      uuid: 13b0a18c-007a-6ac9-ffffcdd30fe47876
      value: >-
        setComfortTemperature/{{
        states('sensor.salon_temperatura_objetivo')|float+0.5}}
mode: single
icon: mdi:thermometer-chevron-up
```
**This is my sensor in 'configuration.yaml':**
```
sensor:
  - name: salon_temperatura_objetivo
    platform: loxone
    uuidAction: "13b0a18c-007a-6ac3-ffff23b39669f00a"
    unit_of_measurement: "°C"
    device_class: "temperature"
    state_class: "total"
```

**And this is my 'LoxAPP3.json' file:**
```
"13b0a18c-007a-6ac9-ffffcdd30fe47876": {
            "name": "Clima",
            "type": "IRoomController",
            "uuidAction": "13b0a18c-007a-6ac9-ffffcdd30fe47876",
            "room": "13af4407-03bd-112b-ffff1d95d609bd2a",
            "cat": "13af4407-0393-0ff0-ffff1d95d609bd2a",
            "defaultRating": 10,
            "isFavorite": true,
            "isSecured": false,
            "details": {
                "restrictedToMode": 0,
                "temperatures": {
                    "0": {
                        "isAbsolute": false
                    },
                    "1": {
                        "isAbsolute": true
                    },
                    "2": {
                        "isAbsolute": true
                    },
                    "3": {
                        "isAbsolute": true
                    },
                    "4": {
                        "isAbsolute": true
                    },
                    "5": {
                        "isAbsolute": false
                    },
                    "6": {
                        "isAbsolute": false
                    }
                },
                "format": "%.1f°"
            },
            "states": {
                "tempTarget": "13b0a18c-007a-6ac3-ffff23b39669f00a",
                "tempActual": "13b0a18c-007a-6a9f-ffff23b39669f00a",
                "error": "13b0a18c-007a-6ac1-ffff23b39669f00a",
                "mode": "13b0a18c-007a-6abf-ffff23b39669f00a",
                "serviceMode": "13b0a18c-007a-6ac0-ffff23b39669f00a",
                "currHeatTempIx": "13b0a18c-007a-6a94-ffff23b39669f00a",
                "currCoolTempIx": "13b0a18c-007a-6a95-ffff23b39669f00a",
                "override": "13b0a18c-007a-6ac6-ffff23b39669f00a",
                "isPreparing": "13b0a18c-007a-6ac7-ffff23b39669f00a",
                "valveHeat": "13b0a18c-007a-6ab6-ffff23b39669f00a",
                "valveCool": "13b0a18c-007a-6aba-ffff23b39669f00a",
                "openWindow": "13b0a18c-007a-6aa0-ffff23b39669f00a",
                "stop": "13b0a18c-007a-6aa7-ffff23b39669f00a",
                "overrideTotal": "13b0a18c-007a-6a99-ffff23b39669f00a",
                "movement": "13b0a18c-007a-6a98-ffff23b39669f00a",
                "manualMode": "13b0a18c-007a-6a9a-ffff23b39669f00a",
                "temperatures": ["13b0a18c-007a-6aa8-ffff23b39669f00a", "13b0a18c-007a-6aa9-ffff23b39669f00a", "13b0a18c-007a-6aaa-ffff23b39669f00a", "13b0a18c-007a-6aad-ffff23b39669f00a", "13b0a18c-007a-6aae-ffff23b39669f00a", "13b0a18c-007a-6aac-ffff23b39669f00a", "13b0a18c-007a-6aab-ffff23b39669f00a"]
            },
            "subControls": {
                "13b0a18c-007a-6a92-ffff23b39669f00a": {
                    "name": "Heating",
                    "type": "IRCDaytimer",
                    "uuidAction": "13b0a18c-007a-6a92-ffff23b39669f00a",
                    "defaultRating": 0,
                    "isFavorite": false,
                    "isSecured": false,
                    "details": {
                        "analog": true,
                        "format": "%.1f°"
                    },
                    "states": {
                        "entriesAndDefaultValue": "13b0a18c-007a-6a92-ffff23b39669f00a",
                        "mode": "13b0a18c-007a-6ac4-ffff23b39669f00a",
                        "modeList": "13b0a18c-007a-6a96-ffff23b39669f00a",
                        "value": "13b0a18c-007a-6a94-ffff23b39669f00a"
                    }
                },
                "13b0a18c-007a-6a93-ffff23b39669f00a": {
                    "name": "Cooling",
                    "type": "IRCDaytimer",
                    "uuidAction": "13b0a18c-007a-6a93-ffff23b39669f00a",
                    "defaultRating": 0,
                    "isFavorite": false,
                    "isSecured": false,
                    "details": {
                        "analog": true,
                        "format": "%.1f°"
                    },
                    "states": {
                        "entriesAndDefaultValue": "13b0a18c-007a-6a93-ffff23b39669f00a",
                        "mode": "13b0a18c-007a-6ac5-ffff23b39669f00a",
                        "modeList": "13b0a18c-007a-6a97-ffff23b39669f00a",
                        "value": "13b0a18c-007a-6a95-ffff23b39669f00a"
                    }
                }
            }
        }
```
Thanks in advance for any help.

**Comment by JoDehli** [comment]
The command is different for a roomcontroller v1.

I think it is settemp. Replace it and try.

**Comment by Enrique555** [comment]
> The command is different for a roomcontroller v1.
> 
> I think it is settemp. Replace it and try.
> 
> You can look each command in the structure file pdf provided from locone.
> 
> https://www.loxone.com/dede/wp-content/uploads/sites/2/2022/06/1300_Structure-File.pdf

I have tried with that function (gettemp) but it hasn't worked. Can you help me? This is my new script:
```
alias: Loxone Test
sequence:
  - service: loxone.event_websocket_command
    data_template:
      uuid: 13b0a18c-007a-6ac9-ffffcdd30fe47876
      value: settemp/{{ states('sensor.salon_temperatura_objetivo')|float+1}}
mode: single
icon: mdi:thermometer-chevron-up
```
On the other hand, do you know how I can upgrade to IRoomControllerV2?
