### ISSUE TITLE
Does not enable new devices or entities even after reload

### ISSUE THREAD

**Issue by I-am-OK-86** [JoDehli/PyLoxone#178]
**Which Model do you use from loxone? Miniserver? Gen2?**

**Which software version does your loxone use?** 14.03.28

**How did you install HomeAssistant? Over Hassio or manual install?** manual

**Which Version do you use of HomeAssistant?** 10.1

**Describe the bug**
I created a new switch in Loxone but it is not available in Py Loxone even after reload

**Paste the error log with the following settings:** 

There is no error log. It is just not there, neither under devices nor under entities.

```yaml
logger:
  default: warning
  logs:
    homeassistant: warning
    homeassistant.helpers: warning
    custom_components.loxone: debug
    custom_components.loxone.api: debug
```
