### ISSUE TITLE
Unable to prepare setup for platform loxone.climate

### ISSUE THREAD

**Issue by vicfalls** [JoDehli/PyLoxone#179]
**Which Model do you use from loxone? Miniserver? Gen1 or Gen2?**
Miniserver Go Gen1

**Which software version does your loxone use?**
14.0.3.28
**How did you install HomeAssistant? Over Hassio or manual install?**
Hassio

**Which Version do you use of HomeAssistant?**
Home Assistant 2023.4.6
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230411.1 - latest

**Describe the bug**

**Paste the error log with the following settings:**
```yaml
logger:
  default: warning
  logs:
    Logger: homeassistant.setup
Source: setup.py:347 
First occurred: 11:10:35 (2 occurrences) 
Last logged: 11:10:35

Unable to prepare setup for platform loxone.climate: Platform not found (cannot import name 'TEMP_CELSIUS' from 'homeassistant.components.climate' (/usr/src/homeassistant/homeassistant/components/climate/__init__.py)).

Unable to prepare setup for platform loxone.climate: Platform not found (cannot import name 'TEMP_CELSIUS' from 'homeassistant.components.climate' (/usr/src/homeassistant/homeassistant/components/climate/__init__.py)).
    custom_components.loxone: debug
    custom_components.loxone.api: debug
```
