### ISSUE TITLE
Custom Sensors State are unavailable

### ISSUE THREAD

**Issue by AndreWeberHH** [JoDehli/PyLoxone#182]
**Which Model do you use from loxone? Miniserver? Gen1 or Gen2?**
Gen2

**Which software version does your loxone use?**
14.1.5.9

**How did you install HomeAssistant? Over Hassio or manual install?**
Hassio

**Which Version do you use of HomeAssistant?**
2023.5.2

**Describe the bug**
I defined a custom sensor, bit the state is always undefined. I tried some hints from others but without any change.

**Sensor 1**
<img width="528" alt="image" src="https://github.com/JoDehli/PyLoxone/assets/31306551/d91e47cd-0920-4693-8f7c-254f5809f74c">
```yaml
sensor
  - platform: loxone
    name: "wohnungsstatus"
    uuidAction: "14ffb3c0-0061-38f8-ffff516fd68d1524"
    unit_of_measurement: "none"
    device_class: "number"
    state_class: "none"
```
<img width="1042" alt="image" src="https://github.com/JoDehli/PyLoxone/assets/31306551/8327f757-f8c3-48b0-bdfd-1dffe1e4cf66">

**Sensor 2**
<img width="370" alt="image" src="https://github.com/JoDehli/PyLoxone/assets/31306551/3314bac8-d3a6-4676-af3b-b29e95fd24f3">
```yaml
sensor
  - platform: loxone
    name: "wohnstat_fruestueck"
    uuidAction: "14ffb53c-009b-ce89-ffff516fd68d1524"
    unit_of_measurement: "none"
    device_class: "number"
    state_class: "none"
```
<img width="1047" alt="image" src="https://github.com/JoDehli/PyLoxone/assets/31306551/182f85c4-0e91-469d-ad0e-4315baa7943b">

**Comment by JoDehli** [comment]
@AndreWeberHH if you want to get the value from the radio you must use the "activeOutput" uuid for the 
uuidAction  and delete the device_class and the state_class from the sensor in the yaml.

```yaml
sensor
  - platform: loxone
    name: "wohnstat_fruestueck"
    uuidAction: "14ffb53c-009b-ce89-ffff516fd68d1524" --> Change this to "activeOutput"
    unit_of_measurement: "none"
    device_class: "number"   ---> Delete this!!
    state_class: "none"         ---> Delete this!!
```

Then restart homeassistant. **Maybe a new sensor is created so make sure you search for the new sensor if you get still the unavailable message for the already included sensor!!!** 

If everything works you get the value 0 to 4 in you example. It would be nice to get the mapped value direct from the sensor for example 4 --> early bird but you can do that with another template sensor which uses this sensor as an input.

**Comment by JoDehli** [comment]
@AndreWeberHH If you want to switch the radio from home assistant you can do that with a helper input_select. If you do not know how to use a helper search for helper and home assistant. The are very handy.

First you define a helper like this: 
![image](https://github.com/JoDehli/PyLoxone/assets/32484282/e21ab4d5-9967-4d06-b7d4-84cef8b39ed4)

As you can see the values are the same as you defined it in loxone with one difference the off case. Here loxone accepts as command only reset or Reset. So this is the only restriction. 

So now you have a input that does nothing. Now you have to make a automation which is triggered every time when the values changes for that input_select.

The automation looks like this: 
![image](https://github.com/JoDehli/PyLoxone/assets/32484282/7a473c8f-1f27-4854-8d77-72c55e2e1617)


and looks like this in yaml: 

```yaml
alias: Mode Radio Switcher
description: ""
trigger:
  - platform: state
    entity_id:
      - input_select.radio
condition: []
action:
  - service: loxone.event_websocket_command
    data:
      uuid: 1710a542-01df-234c-ffff403fb0c34b9e
      value: "{{states('input_select.radio')}}"
mode: single
```
