### ISSUE TITLE
If you want to Turn on / off multiple lights within a LightControllerV2 at the same time using a script a delay must be added!

### ISSUE THREAD

**Issue by ascha191** [JoDehli/PyLoxone#317]
### Describe the bug
Turn on / off multiple lights within a LightControllerV2 at the same time does not work.
Only 2 of 4 lamps are switched on/off at any one time.
i have tested it with a homeassistant script and it needs at least a delay of 150ms so that all lamps are switched reliably.
That's bad because I can't tell the voice assistant to turn off all the lights.

does not work:
```
alias: loxtest
sequence:
  - action: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: light.licht_keller_keller1
  - action: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: light.licht_keller_keller2
  - action: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: light.licht_keller_keller3
  - action: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: light.licht_keller_keller4
```

work:
```
alias: loxtest
sequence:
  - action: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: light.licht_keller_keller1
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 150
  - action: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: light.licht_keller_keller2
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 150
  - action: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: light.licht_keller_keller3
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 150
  - action: light.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: light.licht_keller_keller4
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 150
```

### Firmware of your Miniserver

14.2.6.16 (latest)

### HomeAssistant install method

Hassio 

### Version of HomeAssistant

Core
2024.10.4
Supervisor
2024.11.2
Operating System
13.1
Frontend
20241002.4

### Version of Pyloxone

0.6.16

### Update pyloxone

yes

### Log

Settings for the log can be found on the main page under the section Log Configuration
