### ISSUE TITLE
push buttons rapidly switch on and off when controlling from hassio

### ISSUE THREAD

**Issue by koraysels** [JoDehli/PyLoxone#53]
hi, i installed everything correctly i guess. I can see my loxone lights. but when I flip a switch it is handled as 2 pulses somehow.. It are pushbuttons in my loxone config. But it gets displayed as switches in homeassistant.

How did you fix this ?

**Comment by JoDehli** [comment]
In HA there is no push button. It is normal that the switch goes back to the off position when on the loxone side is a push button.
In my configuration I do it like this with a template switch:

```yaml
platform: template
switches:
  fernseher_switch_combined:
    friendly_name: "Fernseher Licht"
    value_template: "{{ is_state('sensor.steckdose_fernseher_licht', 'on') }}"
    turn_on:
      service: switch.turn_on
      data:
        entity_id: switch.steckdose_fernseher_licht_an
    turn_off:
      service: switch.turn_on
      data:
        entity_id: switch.steckdose_fernseher_licht_aus
```

Both switches are pushbutton on the loxone side. And the resulting switch is acting like you expected.
