### ISSUE TITLE
Sensors

### ISSUE THREAD

**Issue by Ceylan-Geysemans** [JoDehli/PyLoxone#55]
Hey,

Why is it that i cannot give my `InfoOnlyAnalog` sensors an `InfoOnlyDigital` sensors a `device_class` in the config.yaml file?
I would lik to see my sensors in homekit but without proper configuration they won't pop up in homekit, the temperature sensors are the only ones that work but I have humidity sensor and door contacts where I cannot get the feedback from to homekit. 
Is there a work around for this? 
Thanks in advance and keep up the good work!

````
sensor:
  - platform: loxone
    name: "Temprature bureau"
    uuidAction: "13355200-01e4-17cd-ffff1ba65e9e54c4"
    unit_of_measurement: "°C"
  - platform: loxone
    name: "Temprature slaapkamer Ceylan"
    uuidAction: "13363370-0330-e7f1-ffff1ba65e9e54c4"
    unit_of_measurement: "°C"
  - platform: loxone
    name: "Humidity slaapkamer Ceylan"
    device_class: humidity
    uuidAction: "13363370-0330-e7f5-ffff1ba65e9e54c4"
    unit_of_measurement: "%"
  - platform: loxone
    name: "Door sensor contact garage"
    device_class: door
    uuidAction: "132c213e-01de-9686-ffff1ba65e9e54c4"
````

**Comment by JoDehli** [comment]
@Ceylan-Geysemans  I had never the requirement to change that. So I did not implement it. Please try the dev branch
with additional device_class in the yaml for example:

```yaml
sensor:
  - platform: loxone
    name: "Temprature bureau"
    uuidAction: "13355200-01e4-17cd-ffff1ba65e9e54c4"
    unit_of_measurement: "°C"
   device_class: "temperature"
```
You must use the correct device class from homeassistant.
