### ISSUE TITLE
Help discovering state Loxone motion sensor

### ISSUE THREAD

**Issue by DavidOnSec** [JoDehli/PyLoxone#85]
Hello,

First of all thank you very much for making this awesome integration between Loxone and Home Assistant!

Is there a possibility to capture a detection event from a Loxone presence sensor. I'm able to capture an event in HA from a push button and switch (supported by your code).

**Comment by JoDehli** [comment]
@DavidOnSec  Of course the only thing is you must know the id which you want to observe. 

You can get all uuids of all your installation by following these steps: 
https://github.com/JoDehli/PyLoxone/tree/dev#how-do-you-get-the-uuid

If you want to observe an presents detector you will find something like this:

```yaml
        "17d4b2a6-021c-a002-ffff403fb0c34b9e": {
            "name": "Pr\u00e4senz",
            "type": "PresenceDetector",
            "uuidAction": "17d4b2a6-021c-a002-ffff403fb0c34b9e",
            "room": "13efd3e5-019d-8ad2-ffff403fb0c34b9e",
            "cat": "152c22de-0338-94b5-ffff403fb0c34b9e",
            "defaultRating": 0,
            "isFavorite": false,
            "isSecured": false,
            "details": {
                "jLockable": true,
                "text": {
                    "on": "Aktiv",
                    "off": "Inaktiv"
                }
            },
            "states": {
                "jLocked": "97d4b2a6-021c-9ff4-ffff5a3f44c96e13",
                "active": "17d4b2a6-021c-9ffb-ffff5a3f44c96e13",
                "locked": "17d4b2a6-021c-9ff4-ffff5a3f44c96e13",
                "events": "17d4b2a6-021c-9ffa-ffff5a3f44c96e13",
                "activeSince": "17d4b2a6-021c-9fef-ffff5a3f44c96e13",
                "infoText": "17d4b2a6-021c-9ff0-ffff5a3f44c96e13"
            },
            "subControls": {
                "17d4b2a6-021c-9fee-ffff5a3f44c96e13/sensors": {
                    "name": "sensors",
                    "type": "Tracker",
                    "uuidAction": "17d4b2a6-021c-9fee-ffff5a3f44c96e13/sensors",
                    "defaultRating": 0,
                    "isFavorite": false,
                    "isSecured": false,
                    "details": {
                        "maxEntries": 20
                    },
                    "states": {
                        "entries": "17d4b2a6-021c-9fee-ffff5a3f44c96e13"
                    }
                }
            }
        },
```


If you want to know exactly what this means you can download this document: 
https://www.loxone.com/enen/wp-content/uploads/sites/2/2021/06/1201_Structure-File.pdf

But if you want only the binary state of this sensor you can make a custom loxone sensor by inserting 
this in your configuration.yaml

```yaml
sensor:
  - platform: loxone
    name: Motion Sensor
    uuidAction: "17d4b422-0228-c713-fffff067703a9801"
    device_class: "motion"
```
Of course with your uuid of your motion sensors. 

Hope this helps.
