### ISSUE TITLE
`platform` misspelling as `plattform`

### ISSUE THREAD

**Issue by joth76** [JoDehli/PyLoxone#92]
I noticed in that the state events in home assistant have misspelling in their attributes. It should be `platform: loxone`, not `plattform: loxone`.

```
    attributes:
      uuid: xxxx
      device_typ: analog_sensor
      plattform: loxone
      category: Heating & Cooling
      unit_of_measurement: °
      icon: mdi:chart-bell-curve
      friendly_name: Xxx
```

The error is consistent across the project:

```
~/PyLoxone$ grep -R plattform *
custom_components/loxone/__init__.py:                        if "plattform" in attr and attr["plattform"] == DOMAIN:
custom_components/loxone/alarm_control_panel.py:            "plattform": "loxone",
custom_components/loxone/climate.py:            "plattform": "loxone",
custom_components/loxone/cover.py:            "plattform": "loxone",
custom_components/loxone/cover.py:            "plattform": "loxone",
custom_components/loxone/cover.py:            "plattform": "loxone",
custom_components/loxone/light.py:            "plattform": "loxone",
custom_components/loxone/light.py:            "plattform": "loxone",
custom_components/loxone/light.py:            "plattform": "loxone",
custom_components/loxone/light.py:            "plattform": "loxone",
custom_components/loxone/scene.py:            if "plattform" in att and att["plattform"] == DOMAIN:
custom_components/loxone/sensor.py:            "plattform": "loxone",
custom_components/loxone/sensor.py:            "plattform": "loxone",
custom_components/loxone/sensor.py:            "plattform": "loxone",
custom_components/loxone/switch.py:            "plattform": "loxone",
custom_components/loxone/switch.py:            "plattform": "loxone",
custom_components/loxone/switch.py:            "plattform": "loxone",
```

I think it stems back to  this post :-)
https://community.home-assistant.io/t/loxone-smart-home-support/5523/4
